# Generated by Django 3.1.4 on 2020-12-15 21:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patronymic', models.CharField(blank=True, max_length=32, null=True, verbose_name='Отчество')),
                ('team_alias', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Позывной')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Номер телефона')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('characteristic', models.TextField(blank=True, null=True, verbose_name='Характеристика')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Добавлен')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
                ('last_online', models.DateTimeField(blank=True, null=True)),
                ('awards', models.ManyToManyField(blank=True, null=True, to='users.UserAwards')),
                ('events', models.ManyToManyField(blank=True, null=True, related_name='user', to='events.UserEvent')),
                ('position', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='users.userpositions', verbose_name='Должность')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.userrole', verbose_name='Роль')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
    ]
