# Generated by Django 3.1.4 on 2020-12-18 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userawards',
            options={'verbose_name': 'Награда', 'verbose_name_plural': 'Награды'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='users/%Y/%m/%d/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='userawards',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='Награда'),
        ),
    ]
