# Generated by Django 3.1.4 on 2020-12-18 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201218_2305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='awards',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='events',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_online',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='patronymic',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='position',
        ),
    ]
