# Generated by Django 3.1.4 on 2020-12-19 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('users', '0005_auto_20201218_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='awards',
            field=models.ManyToManyField(blank=True, null=True, to='users.UserAwards'),
        ),
        migrations.AddField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Добавлен'),
        ),
        migrations.AddField(
            model_name='profile',
            name='events',
            field=models.ManyToManyField(blank=True, null=True, related_name='user', to='events.UserEvent'),
        ),
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='users/%Y/%m/%d/', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='profile',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.userpositions', verbose_name='Должность'),
        ),
    ]
