# Generated by Django 3.1.4 on 2020-12-19 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profile_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='vk_link',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Ссылка ВК'),
        ),
    ]
