# Generated by Django 3.1.4 on 2021-01-02 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_profile_vk_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userawards',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='awards_pic/%Y/%m/%d/', verbose_name='Картинка'),
        ),
    ]
