# Generated by Django 3.1.4 on 2021-01-05 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20210102_1559'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpositions',
            old_name='short_description',
            new_name='description',
        ),
    ]
