# Generated by Django 3.1.4 on 2021-04-09 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20210409_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='division',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Отделение'),
        ),
    ]
