# Generated by Django 3.1.4 on 2020-12-15 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание мероприятия')),
                ('price', models.IntegerField(blank=True, verbose_name='Стоимость')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('location_description', models.CharField(max_length=128, verbose_name='Место проведения')),
                ('location_coord', models.CharField(blank=True, max_length=128, verbose_name='Координаты')),
                ('meeting_point', models.CharField(blank=True, max_length=128, verbose_name='Точка сбора')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('close_reg_at', models.DateTimeField(auto_now=True, verbose_name='Окончание регистрации')),
                ('starting_at', models.DateTimeField(auto_now=True, verbose_name='Начало мероприятия')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_status', models.IntegerField(default=0, verbose_name='Статус регистрации')),
                ('user_payment', models.BooleanField(default=False, verbose_name='Статус оплаты')),
                ('visited', models.BooleanField(default=False, verbose_name='Посещение')),
                ('user_comment', models.TextField(blank=True, verbose_name='Комментарий игрока')),
                ('leader_comment', models.TextField(blank=True, verbose_name='Комментарий пользователя')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.event')),
            ],
        ),
    ]
