# Generated by Django 3.1.4 on 2020-12-15 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание мероприятия'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location_coord',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Координаты'),
        ),
        migrations.AlterField(
            model_name='event',
            name='meeting_point',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Точка сбора'),
        ),
        migrations.AlterField(
            model_name='event',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='userevent',
            name='leader_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий пользователя'),
        ),
        migrations.AlterField(
            model_name='userevent',
            name='user_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий игрока'),
        ),
    ]
