# Generated by Django 3.1.4 on 2021-01-19 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20210119_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='close_reg_at',
            field=models.DateTimeField(verbose_name='Окончание регистрации'),
        ),
    ]
