# Generated by Django 3.1.4 on 2021-02-06 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20210119_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userevent',
            name='user_status',
            field=models.IntegerField(choices=[('0', 'Пойдёт'), ('1', 'Отменил регистрацию'), ('3', 'Пропустил игру')], default=0, verbose_name='Статус регистрации'),
        ),
    ]
