# Generated by Django 3.1.4 on 2021-01-02 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20210102_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='Общий доступ'),
        ),
    ]
